### ISSUE TITLE
Can this be configured in a .remarkrc file?

### ISSUE THREAD

**Issue by ndelangen** [wooorm/remark-toc#14]
The documentation mentions how to configure with the programmatic API, but not the config-file api.

How do I configure this in my `.remarkrc` file?

Here's my `.remarkrc` file:

```json
{
  "plugins": [
    "remark-preset-lint-recommended",
    ["remark-toc", {
      "tight": true,
      
    }],
    ["remark-lint-list-item-indent", false],
    ["remark-lint-code", {"js": {
      "module": "node_modules/remark-lint-code-eslint",
      "options": {
        "fix": true
      }
    }}]
  ]
}
```

**Comment by wooorm** [comment]
You’re already using it right!?

**Comment by ndelangen** [comment]
But it's not actually adding the tocs..

What could I be doing wrong?

**Comment by wooorm** [comment]
How are you running remark? Tip: add the [DEBUG](https://github.com/unifiedjs/unified-args#debugging) env variable.

**Comment by ndelangen** [comment]
Here's how I'm calling remark:
https://github.com/storybooks/storybook/blob/ndelangen/dev/package.json#L49

**Comment by wooorm** [comment]
In `remark . # -- -o to update`, the `#` makes the rest of the line into a comment, if you want to generate files, you do need to pass `-o, --output`, like so: `remark . -o`!

**Comment by ndelangen** [comment]
I know, I'm actually running this:
`npm run lint:markdown -- --o`

**Comment by ndelangen** [comment]
ow I think I've spotted a problem between the keyboard and chair

**Comment by wooorm** [comment]
Is any markdown reformatted? Maybe `-- -o` isn't the proper way to pass flags?

**Comment by ndelangen** [comment]
No it appears no markdown is formatted, strange that was working before..

**Comment by wooorm** [comment]
New npm version? I’m note sure, but I think they switched it around before.
So is it working now?

**Comment by ndelangen** [comment]
So it DOES work when I change my npm script like so:
`
"lint:markdown": "DEBUG=\"*\" remark . -o",
`

**Comment by wooorm** [comment]
Maybe because of the comment? Maybe npm execs like so: `remark . # -- -o to update -o` (where the last `-o` is added from outside the npm script).

**Comment by ndelangen** [comment]
I guess it could be because of the comment, yeah, I'll reset, and try without 👍

**Comment by ndelangen** [comment]
`remark-toc` is adding the tocs correctly now, thanks. 😎

I will stop adding comments to my npm script and dislike json for configuring even more 😒

**Comment by wooorm** [comment]
😛

Alright, good! Feel free to add more issues if you run into stuff, but I’d also like to point out that the [Gitter](https://gitter.im/wooorm/remark) channel is really good for more question-like stuff!
