### ISSUE TITLE
I don't want to delete all of the following, and I don't want to find "Table of Contents". I want to insert toc in the first line of the file

### ISSUE THREAD

**Issue by yueduz** [wooorm/remark-toc#15]
Could it happen

**Comment by wooorm** [comment]
Yes, by creating your own plugin wrapping [`mdast-util-toc`](https://github.com/BarryThePenguin/mdast-util-toc)! [`remark-toc`](https://github.com/wooorm/remark-toc/blob/master/index.js)s source code should help!
