### ISSUE TITLE
redundance of <p>aragraphs in list items

### ISSUE THREAD

**Issue by iamstarkov** [wooorm/remark-toc#3]
If paragraphs can be removed from TOC then it can look a bit better. what do you think?
![screen shot 2015-12-28 at 00 19 26](https://cloud.githubusercontent.com/assets/559321/12012502/c41df1a4-acf8-11e5-872b-8822016b5b7e.png)
![screen shot 2015-12-28 at 00 19 36](https://cloud.githubusercontent.com/assets/559321/12012503/c434113c-acf8-11e5-912c-8d86c96cd6e3.png)
![screen shot 2015-12-28 at 00 19 46](https://cloud.githubusercontent.com/assets/559321/12012504/c45a61ca-acf8-11e5-8c60-1ce5eebe9120.png)
![screen shot 2015-12-28 at 00 19 57](https://cloud.githubusercontent.com/assets/559321/12012505/c45d08da-acf8-11e5-950e-0036e4518652.png)

**Comment by wooorm** [comment]
You should be able to suppress these paragraphs by passing the 'tight' option (see bottom of the options section)!
