### ISSUE TITLE
Expose toc generation as a standalone transformer

### ISSUE THREAD

**Issue by BarryThePenguin** [wooorm/remark-toc#4]
Would it be possible to expose the generation of a toc for a document as it's own remark transformer?

I'd need some guidance, but I'd be happy to contribute this as a PR!

**Comment by wooorm** [comment]
Sure, that’s possible. The [attacher part](https://github.com/wooorm/remark-toc/blob/6e0b351097d42bd8e9fa1475ca44ee9b04252094/index.js#L305-L338) is just a small wrapper around the transformer.

However, something tells me your question is longer than what you put into words: could you elaborate on what you do and don’t want? And why?

**Comment by BarryThePenguin** [comment]
Yeah... I've been playing around with it, I probably haven't thought this through.

I'm looking at having the toc being a separate chunk of html to the rest of the document, not at the beginning of the document.

My initial thought was having two api methods

1. that builds the toc with options simliar to what is used currently, with the ability to ignore the heading expression
2. that uses the first method, including the default heading expression, to generate the toc and insert it into the top of the document, like the existing attacher method

**Comment by wooorm** [comment]
How would the first heading be detected? E.g., this module starts creating the TOC from the heading after `Table of Contents`, until the end of the document.

Maybe it’s easier to add a TOC heading to the content, use remark-toc, and have a new plug-in move the TOC to another file?

**Comment by BarryThePenguin** [comment]
Currently my toc matches my heading structure, so the first heading is the first item in the toc, second heading is the second item. I haven't found a way in the current implementation that caters for my scenario.

I appreciate you responding quickly, and I fully understand if you don't think this is a suitable addition to your project

**Comment by wooorm** [comment]
Closing. See https://github.com/wooorm/remark-toc/pull/5#issuecomment-229334545 for reasoning.
