### ISSUE TITLE
Indentation of Table of content?

### ISSUE THREAD

**Issue by denysdovhan** [wooorm/remark-toc#7]
I use `tight` option with `remark-toc` and get this result:

```md
-   [Terms](#terms)
    -   [Term 1](#term-1)
    -   [Term 2](#term-2)
    -   [Term 3](#term-3)
-   [Organization](#organization)
-   [Events](#events)
-   [Resources](#resources)
-   [License](#license)
```

Here I have indentation in 4 spaces for each level, but I prefer to use 2 spaces. Is there a way to change indentation level?

**Comment by wooorm** [comment]
👋 

Yup, you can set `listItemIndent` to `1` in the [stringification options](https://github.com/wooorm/remark/tree/master/packages/remark-stringify#options).

**Comment by denysdovhan** [comment]
I didn't understand. If I have this configuration in my `package.json`, where exactly should I pass this option?

```json
{
  "remarkConfig": {
    "plugins": {
      "toc": {
        "tight": true
      }
    }
  }
}
```

**Comment by wooorm** [comment]
Ah, on the CLI you can store that in [`remarkConfig.settings`](https://github.com/wooorm/unified-engine/blob/master/doc/configure.md#settings) (e.g., `remarkConfig: {settings: {listItemIndent: '1'}}`).

**Comment by denysdovhan** [comment]
Thank you 👍 
Works for me!

**Comment by wooorm** [comment]
Perfect!
